import Project from '../../models/project';

export default (id) => {
  return Project.insertMany([{
    resumeId: id,
    title: 'Css Line Drawing',
    imageUrl: 'https://images.corynorris.me/projects/bear.jpg',
    demoUrl: 'https://codepen.io/corynorris/full/ZQLJrx/',
    sourceUrl: 'https://codepen.io/corynorris/pen/ZQLJrx',
    completionDate: new Date('Dec 1, 2016'),
    summary: 'An svg line animation of a bear.',
    tags: ['svg', 'css', 'line-animation', 'javascript'],
  }, {
    resumeId: id,
    title: 'Simon the Game',
    imageUrl: 'https://images.corynorris.me/projects/simon.jpg',
    demoUrl: 'https://codepen.io/corynorris/full/KVzBZZ/',
    sourceUrl: 'https://codepen.io/corynorris/pen/KVzBZZ',
    completionDate: new Date('Dec 1, 2016'),
    summary: 'A game where you you attempt to remember an ever growing sequence.',
    tags: ['css', 'game', 'sass', 'scss', 'javascript'],
  }, {
    resumeId: id,
    title: 'Link Hover Effects',
    imageUrl: 'https://images.corynorris.me/projects/button-styles.jpg',
    demoUrl: 'https://codepen.io/corynorris/full/MKJrwm/',
    sourceUrl: 'https://codepen.io/corynorris/pen/MKJrwm',
    completionDate: new Date('Dec 1, 2016'),
    summary: '10 css-only effects for the mouse hover event.',
    tags: ['css', 'sass', 'scss', 'svg', 'effects'],
  }, {
    resumeId: id,
    title: 'Wobble Rocket',
    imageUrl: 'https://images.corynorris.me/projects/wobble-rocket.jpg',
    demoUrl: 'https://play.google.com/store/apps/details?id=com.LastHackerGames.WobbleRocket',
    sourceUrl: 'https://bitbucket.org/corynorris/wobblerocket/overview',
    completionDate: new Date('Dec 1, 2015'),
    summary: 'A game of dodging obstacles to unlock new rockets.',
    tags: ['java', 'game', 'libgdx', 'android-app'],
  }, {
    resumeId: id,
    title: 'Roman Calculator',
    imageUrl: 'https://images.corynorris.me/projects/roman-calculator.jpg',
    demoUrl: 'https://codepen.io/corynorris/full/wMBKwx/',
    sourceUrl: 'https://codepen.io/corynorris/pen/wMBKwx/',
    completionDate: new Date('Dec 1, 2015'),
    summary: 'A calculator that uses roman numerals.',
    tags: ['css', 'javascript'],
  }, {
    resumeId: id,
    title: 'Quote Machine',
    imageUrl: 'https://images.corynorris.me/projects/quote-machine.jpg',
    demoUrl: 'https://codepen.io/corynorris/full/MKgzGJ/',
    sourceUrl: 'https://codepen.io/corynorris/pen/MKgzGJ/',
    completionDate: new Date('Dec 1, 2015'),
    summary: 'A random quote generator.',
    tags: ['css', 'javascript'],
  }, {
    resumeId: id,
    title: 'Pomodoro Timer',
    imageUrl: 'https://images.corynorris.me/projects/pomodoro.jpg',
    demoUrl: 'https://codepen.io/corynorris/full/EPxjGP/',
    sourceUrl: 'https://codepen.io/corynorris/pen/EPxjGP/',
    completionDate: new Date('Dec 1, 2015'),
    summary: 'A timer that rotates between rest and work periods.',
    tags: ['css', 'javascript'],
  }, {
    resumeId: id,
    title: 'Tic-Tac-Toe',
    imageUrl: 'https://images.corynorris.me/projects/tic-tac-toe.jpg',
    demoUrl: 'https://codepen.io/corynorris/full/OMyMEe/',
    sourceUrl: 'https://codepen.io/corynorris/pen/OMyMEe/',
    completionDate: new Date('Dec 1, 2015'),
    summary: 'A game of tic-tac-toe against an AI.',
    tags: ['css', 'sass', 'scss', 'game', 'ai'],
  }]);
};
